### ISSUE TITLE
@cf commands return [object Set]

### ISSUE THREAD

**Issue by georgibarzev** [jthomas/cfbot#3]
Deploying the app to CF resulted in a syntax error for the "[..." code repeated a few times in the app and that failed the cf push deployment. Is this part of the code essential? Removing the dots seemed to fix the syntax, but lead to a problem with missing slack_token credentials, which could be resolved by hardcoding the credentials in the index.js file. Following these steps the bot successfully connects to slack and responds to the @cf commands, but only returns an object set instead of a list of apps or events.

"@cf apps" 
returns
"Now monitoring the following apps: [object Set]"

CF CLI used: 6.16.1
 "api_version": "2.47.0",

Any thoughts? Thank you in advance.

**Comment by jthomas** [comment]
The '...' code is using the [ES6 array spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) operation. I'm guessing the application has been executed in a Node.js environment <= 0.12.0 to cause this error. ES6 functionality for array spreading wasn't introduced until Node.js v4. 

Can you verify you're using a Node.js runtime that's above v4? You can enforce the correct Node runtime through the package.json, as explained [here](https://github.com/cloudfoundry/nodejs-buildpack#options).

**Comment by georgibarzev** [comment]
Thank you very much for the quick reply. 

I tried 

  "engines": {
    "node": "4.2.3"
  }

resulting in: 

-----> Installing binaries
       engines.node (package.json):  4.2.3
       engines.npm (package.json):   unspecified (use default)
       Downloading and installing node 4.2.3...
       Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/e3b1d3c3-c64a-4cc9-a05e-971660b3cc24_4c3d273d4bdf966b701b46deca622dd9925969f3/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_node_node-4.2.3-linux-x64.tgz]
       Using default npm version: 2.14.7

but unfortunately it still failed on the '...' code. Could the problem be in "cf-nodejs-client": "^0.12.0" or some of the other dependencies?

**Comment by jthomas** [comment]
Can you paste in the exact error log caused by the code without your modifications? 
I'll see if I can reproduce.

**Comment by georgibarzev** [comment]
```
2016-03-10T14:54:31.50+0000 [API/0]      OUT Updated app with guid 02e05cf0-e365-42fa-8c96-e893b729e41c ({"state"=>"STOPPED"})
2016-03-10T14:54:38.22+0000 [API/0]      OUT Updated app with guid 02e05cf0-e365-42fa-8c96-e893b729e41c ({"state"=>"STARTED"})
2016-03-10T14:55:00.71+0000 [App/0]      ERR     at Module._compile (module.js:435:26)
2016-03-10T14:55:00.71+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:55:00.76+0000 [App/0]      ERR npm ERR! Linux 3.19.0-47-generic
2016-03-10T14:55:00.76+0000 [App/0]      ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"
2016-03-10T14:55:00.76+0000 [App/0]      ERR npm ERR! node v4.2.3
2016-03-10T14:55:00.77+0000 [App/0]      ERR npm ERR! npm  v2.14.7
2016-03-10T14:55:00.77+0000 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-03-10T14:55:00.77+0000 [App/0]      ERR npm ERR! cfbot@0.1.1 start: `node index.js`
2016-03-10T14:55:00.77+0000 [App/0]      ERR npm ERR! Exit status 1
2016-03-10T14:55:00.77+0000 [App/0]      ERR npm ERR! 
2016-03-10T14:55:00.77+0000 [App/0]      ERR npm ERR! Failed at the cfbot@0.1.1 start script 'node index.js'.
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR! This is most likely a problem with the cfbot package,
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR! not with npm itself.
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR!     node index.js
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR! You can get their info via:
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR!     npm owner ls cfbot
2016-03-10T14:55:00.78+0000 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-03-10T14:55:00.79+0000 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-03-10T14:55:00.79+0000 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-03-10T14:55:00.88+0000 [API/0]      OUT App instance exited with guid 02e05cf0-e365-42fa-8c96-e893b729e41c payload: {"cc_partition"=>"default", "droplet"=>"02e05cf0-e365-42fa-8c96-e893b729e41c", "version"=>"829795e6-cedd-47a5-8f84-d4e862664887", "instance"=>"b3faa33427cd480c8adbbfd423c6283b", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1457621700}
2016-03-10T14:55:38.96+0000 [DEA/1]      OUT Starting app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:55:41.07+0000 [App/0]      OUT 
2016-03-10T14:55:41.07+0000 [App/0]      OUT > cfbot@0.1.1 start /home/vcap/app
2016-03-10T14:55:41.07+0000 [App/0]      OUT > node index.js
2016-03-10T14:55:41.20+0000 [App/0]      ERR /home/vcap/app/lib/cf_bot.js:44
2016-03-10T14:55:41.20+0000 [App/0]      ERR       + [...this.filters[type].filters].join(', ')
2016-03-10T14:55:41.20+0000 [App/0]      ERR          ^^^
2016-03-10T14:55:41.20+0000 [App/0]      ERR SyntaxError: Unexpected token ...
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at exports.runInThisContext (vm.js:53:16)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Module._compile (module.js:414:25)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Module.load (module.js:356:32)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Function.Module._load (module.js:311:12)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Module.require (module.js:366:17)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at require (module.js:385:17)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/index.js:3:15)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Module._compile (module.js:435:26)
2016-03-10T14:55:41.20+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! Linux 3.19.0-47-generic
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! node v4.2.3
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! npm  v2.14.7
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! cfbot@0.1.1 start: `node index.js`
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! Exit status 1
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! 
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! Failed at the cfbot@0.1.1 start script 'node index.js'.
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! This is most likely a problem with the cfbot package,
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! not with npm itself.
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR!     node index.js
2016-03-10T14:55:41.21+0000 [App/0]      ERR npm ERR! You can get their info via:
2016-03-10T14:55:41.22+0000 [App/0]      ERR npm ERR!     npm owner ls cfbot
2016-03-10T14:55:41.22+0000 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-03-10T14:55:41.22+0000 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-03-10T14:55:41.22+0000 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-03-10T14:55:41.24+0000 [API/0]      OUT App instance exited with guid 02e05cf0-e365-42fa-8c96-e893b729e41c payload: {"cc_partition"=>"default", "droplet"=>"02e05cf0-e365-42fa-8c96-e893b729e41c", "version"=>"829795e6-cedd-47a5-8f84-d4e862664887", "instance"=>"1f0e02570a5a48a8a36628d098187ad6", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1457621741}
2016-03-10T14:56:28.81+0000 [DEA/2]      OUT Starting app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:56:33.50+0000 [App/0]      OUT 
2016-03-10T14:56:33.50+0000 [App/0]      OUT > cfbot@0.1.1 start /home/vcap/app
2016-03-10T14:56:33.50+0000 [App/0]      OUT > node index.js
2016-03-10T14:56:33.65+0000 [App/0]      ERR /home/vcap/app/lib/cf_bot.js:44
2016-03-10T14:56:33.65+0000 [App/0]      ERR       + [...this.filters[type].filters].join(', ')
2016-03-10T14:56:33.65+0000 [App/0]      ERR          ^^^
2016-03-10T14:56:33.65+0000 [App/0]      ERR SyntaxError: Unexpected token ...
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at exports.runInThisContext (vm.js:53:16)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Module._compile (module.js:414:25)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Module.load (module.js:356:32)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Function.Module._load (module.js:311:12)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Module.require (module.js:366:17)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at require (module.js:385:17)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/index.js:3:15)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Module._compile (module.js:435:26)
2016-03-10T14:56:33.65+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:56:33.66+0000 [App/0]      ERR npm ERR! Linux 3.19.0-47-generic
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! node v4.2.3
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! npm  v2.14.7
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! cfbot@0.1.1 start: `node index.js`
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! Exit status 1
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! 
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! Failed at the cfbot@0.1.1 start script 'node index.js'.
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! This is most likely a problem with the cfbot package,
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! not with npm itself.
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-03-10T14:56:33.67+0000 [App/0]      ERR npm ERR!     node index.js
2016-03-10T14:56:33.68+0000 [App/0]      ERR npm ERR! You can get their info via:
2016-03-10T14:56:33.68+0000 [App/0]      ERR npm ERR!     npm owner ls cfbot
2016-03-10T14:56:33.68+0000 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-03-10T14:56:33.68+0000 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-03-10T14:56:33.68+0000 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-03-10T14:56:33.73+0000 [API/0]      OUT App instance exited with guid 02e05cf0-e365-42fa-8c96-e893b729e41c payload: {"cc_partition"=>"default", "droplet"=>"02e05cf0-e365-42fa-8c96-e893b729e41c", "version"=>"829795e6-cedd-47a5-8f84-d4e862664887", "instance"=>"c735c3e89bda4ea68799d9c1cdc03fde", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1457621793}
2016-03-10T14:56:37.78+0000 [DEA/2]      OUT Removing crash for app with id 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:56:37.78+0000 [DEA/2]      OUT Stopping app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:56:37.78+0000 [DEA/2]      OUT Stopped app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:57:18.92+0000 [DEA/2]      OUT Starting app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:57:23.14+0000 [App/0]      OUT 
2016-03-10T14:57:23.14+0000 [App/0]      OUT > cfbot@0.1.1 start /home/vcap/app
2016-03-10T14:57:23.14+0000 [App/0]      OUT > node index.js
2016-03-10T14:57:23.30+0000 [App/0]      ERR /home/vcap/app/lib/cf_bot.js:44
2016-03-10T14:57:23.30+0000 [App/0]      ERR       + [...this.filters[type].filters].join(', ')
2016-03-10T14:57:23.30+0000 [App/0]      ERR          ^^^
2016-03-10T14:57:23.30+0000 [App/0]      ERR SyntaxError: Unexpected token ...
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at exports.runInThisContext (vm.js:53:16)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Module._compile (module.js:414:25)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Module.load (module.js:356:32)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Function.Module._load (module.js:311:12)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Module.require (module.js:366:17)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at require (module.js:385:17)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/index.js:3:15)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Module._compile (module.js:435:26)
2016-03-10T14:57:23.30+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-03-10T14:57:23.32+0000 [App/0]      ERR npm ERR! Linux 3.19.0-47-generic
2016-03-10T14:57:23.32+0000 [App/0]      ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"
2016-03-10T14:57:23.32+0000 [App/0]      ERR npm ERR! node v4.2.3
2016-03-10T14:57:23.32+0000 [App/0]      ERR npm ERR! npm  v2.14.7
2016-03-10T14:57:23.32+0000 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! cfbot@0.1.1 start: `node index.js`
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! Exit status 1
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! 
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! Failed at the cfbot@0.1.1 start script 'node index.js'.
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! This is most likely a problem with the cfbot package,
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! not with npm itself.
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR!     node index.js
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! You can get their info via:
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR!     npm owner ls cfbot
2016-03-10T14:57:23.33+0000 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-03-10T14:57:23.34+0000 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-03-10T14:57:23.34+0000 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-03-10T14:57:23.38+0000 [API/0]      OUT App instance exited with guid 02e05cf0-e365-42fa-8c96-e893b729e41c payload: {"cc_partition"=>"default", "droplet"=>"02e05cf0-e365-42fa-8c96-e893b729e41c", "version"=>"829795e6-cedd-47a5-8f84-d4e862664887", "instance"=>"803f2bb07440429fa714c00271c92aae", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1457621843}
2016-03-10T14:57:27.84+0000 [DEA/2]      OUT Removing crash for app with id 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:57:27.84+0000 [DEA/2]      OUT Stopping app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
2016-03-10T14:57:27.84+0000 [DEA/2]      OUT Stopped app instance (index 0) with guid 02e05cf0-e365-42fa-8c96-e893b729e41c
```

**Comment by jthomas** [comment]
I mistakenly thought that array spreading was available in node v4, it wasn't introduced until v5. 
I've updated the node engine flag in package.json to reflect this.
Can you retry? CF should auto-update to use v5 and it _should_ work!

**Comment by georgibarzev** [comment]
I can confirm it works with v5. Thanks for the help, much appreciated :)
